// Generated by CoffeeScript 1.9.0
(function() {
  var Server, app, express, onHttpRequest, router, server;

  Server = require('./server');

  server = new Server({
    http: false,
    udp: false
  });

  onHttpRequest = server.onHttpRequest.bind(server);

  express = require('express');

  app = express();

  router = express.Router();

  router.use(function(req, res, next) {
    console.log('Caught a request');
    return next();
  });

  router.get('/announce/:id', function(req, res, next) {
    console.log(req.params.id);
    res.send('Lose!');
    return next();
  });

  app.use('/', router);

  app.get('/announce', onHttpRequest);

  app.get('/scrape', onHttpRequest);

  app.listen(3000, function() {
    return console.log('Tracker listening on a port...');
  });

}).call(this);

//# sourceMappingURL=app.js.map
